/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package easycareprojeto;

/**
 *
 * @author João
 */
public class TelaHome extends javax.swing.JFrame {

   
    public TelaHome() {
        initComponents();
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeHome = new javax.swing.JLabel();
        botaoFecharHome = new javax.swing.JButton();
        btnCadastrarPaciente = new javax.swing.JButton();
        btnCadastrarMedicamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1033, 701));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        lblNomeHome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(lblNomeHome);
        lblNomeHome.setBounds(200, 100, 190, 20);

        botaoFecharHome.setBackground(new java.awt.Color(82, 221, 104));
        botaoFecharHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechaHome.png"))); // NOI18N
        botaoFecharHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoFecharHome.setBorderPainted(false);
        botaoFecharHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharHomeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFecharHome);
        botaoFecharHome.setBounds(880, 20, 130, 70);

        btnCadastrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Group 10.png"))); // NOI18N
        btnCadastrarPaciente.setBorder(null);
        btnCadastrarPaciente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCadastrarPaciente.setMaximumSize(new java.awt.Dimension(253, 57));
        btnCadastrarPaciente.setMinimumSize(new java.awt.Dimension(253, 57));
        btnCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarPaciente);
        btnCadastrarPaciente.setBounds(720, 490, 260, 60);

        btnCadastrarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Group 11.png"))); // NOI18N
        btnCadastrarMedicamento.setBorder(null);
        btnCadastrarMedicamento.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCadastrarMedicamento.setMaximumSize(new java.awt.Dimension(253, 57));
        btnCadastrarMedicamento.setMinimumSize(new java.awt.Dimension(253, 57));
        btnCadastrarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMedicamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarMedicamento);
        btnCadastrarMedicamento.setBounds(430, 490, 260, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoHome.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharHomeActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoFecharHomeActionPerformed

    private void btnCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPacienteActionPerformed
        TelaCadastroPaciente cadastroP = new TelaCadastroPaciente();
        cadastroP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarPacienteActionPerformed

    private void btnCadastrarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMedicamentoActionPerformed
        TelaCadastroMedicamento cadastroM = new TelaCadastroMedicamento();
        cadastroM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFecharHome;
    public javax.swing.JButton btnCadastrarMedicamento;
    public javax.swing.JButton btnCadastrarPaciente;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblNomeHome;
    // End of variables declaration//GEN-END:variables
}
